### ISSUE TITLE
Transparency with trapdoors & spiderwebs when connected to blocks (1.20.2) macos

### ISSUE THREAD

**Issue by protorota** [GeForceLegend/Minecraft-Default-3D#31] opened 2024-04-15 05:33 UTC
when enabled, any blocks that are against trapdoors and spiderwebs cause the gaps in the block to be transparent and the world map behind to become visible.

May happen with other items but have only noticed trapdoors & webs so far

Have tried rearranging order of resource packs to no effect

**Comment by GeForceLegend** [comment] 2024-04-16 09:38
Any screen shots? And if there is, any mods?

**Comment by GeForceLegend** [comment] 2024-04-19 01:40
> Hey @GeForceLegend, I have this issue aswell. I'm running `1.20.1` modded minecraft on Fabric. It seems to affect the vanilla trap door. Taking of the resource pack fixes the issue
> 
> Screenshot: ![image](https://private-user-images.githubusercontent.com/131410131/323575363-1d89ddea-1f6b-4729-9d26-087b82dff34c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0OTA4NDgsIm5iZiI6MTcxMzQ5MDU0OCwicGF0aCI6Ii8xMzE0MTAxMzEvMzIzNTc1MzYzLTFkODlkZGVhLTFmNmItNDcyOS05ZDI2LTA4N2I4MmRmZjM0Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxOVQwMTM1NDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kOTc5YzFiNmZiOWYyN2IwN2VjNjBkMmIwYjVmZTI1ODYzNTQ3ZGE2MWEwZDdkNjU2ODA0MjAxYTJmOGRmNzYwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.VtcuD5u881Z08PkIZMHyVzeHhk8CPfLUxeKR_DeWrlc)

Are you using any mods? I can't see this when running with just Sodium and Iris.

**Comment by GeForceLegend** [comment] 2024-04-29 01:53
If all of you can't provide detailed information, I'll close this issue as considered causing by other mods

**Comment by protorota** [comment] 2024-04-29 07:57
I will have a chance to test later today without mods etc

**Comment by GeForceLegend** [comment] 2024-05-05 02:55
Closed as no more infomation, considered as caused by other mods. If you find anything, you can reopen it later.

**Closed as completed by GeForceLegend** 2024-05-05 02:55 UTC
